module.exports = [
    {
        rank: 1,
        rank_last_week: 0,
        weeks_on_list: 1,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '1635574048',
        primary_isbn13: '9781635574043',
        publisher: 'Bloomsbury',
        description: 'Passion arises between Bryce Quinlan and Hunt Athalar as they seek to avenge the deaths of Bryce’s friends.',
        price: 0,
        title: 'HOUSE OF EARTH AND BLOOD',
        author: 'Sarah J Maas',
        contributor: 'by Sarah J. Maas',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9781635574043.jpg',
        book_image_width: 329,
        book_image_height: 500,
        amazon_product_url: 'https://www.amazon.com/dp/1635574048?tag=NYTBSREV-20&tag=NYTBS-20',
        age_group: '',
        book_review_link: '',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/6f162dc2-b8b1-518f-bf52-00c04159757d'
    },
    {
        rank: 2,
        rank_last_week: 0,
        weeks_on_list: 1,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '0525538232',
        primary_isbn13: '9780525538233',
        publisher: 'Putnam',
        description: 'The 20th book in the Joe Pickett series. A grizzly bear attack and an attempted assassination of a local judge baffle the Wyoming game warden.',
        price: 0,
        title: 'LONG RANGE',
        author: 'CJ Box',
        contributor: 'by C.J. Box',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780525538233.jpg',
        book_image_width: 331,
        book_image_height: 500,
        amazon_product_url: 'https://www.amazon.com/dp/0525538232?tag=NYTBSREV-20&tag=NYTBS-20',
        age_group: '',
        book_review_link: '',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/4f1bf826-8df4-55df-a2b2-983cc9d2bc60'
    },
    {
        rank: 3,
        rank_last_week: 2,
        weeks_on_list: 79,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '0735219095',
        primary_isbn13: '9780735219090',
        publisher: 'Putnam',
        description: 'In a quiet town on the North Carolina coast in 1969, a young woman who survived alone in the marsh becomes a murder suspect.',
        price: 0,
        title: 'WHERE THE CRAWDADS SING',
        author: 'Delia Owens',
        contributor: 'by Delia Owens',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780735219090.jpg',
        book_image_width: 328,
        book_image_height: 495,
        amazon_product_url: 'https://www.amazon.com/Where-Crawdads-Sing-Delia-Owens/dp/0735219095?tag=NYTBS-20',
        age_group: '',
        book_review_link: '',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object], [Object], [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/053b4109-4555-5aa1-9b39-cc40549bcdf0'
    },
    {
        rank: 4,
        rank_last_week: 0,
        weeks_on_list: 1,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '0399179569',
        primary_isbn13: '9780399179563',
        publisher: 'Delacorte',
        description: 'An affair wrecks a marriage and a daughter seeks to get out from her family’s shadow while old dreams and new love are pursued.',
        price: 0,
        title: 'THE NUMBERS GAME',
        author: 'Danielle Steel',
        contributor: 'by Danielle Steel',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780399179563.jpg',
        book_image_width: 328,
        book_image_height: 500,
        amazon_product_url: 'https://www.amazon.com/dp/0399179569?tag=NYTBSREV-20&tag=NYTBS-20',
        age_group: '',
        book_review_link: '',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/72a48fed-fda5-5738-b609-baaf996607ff'
    },
    {
        rank: 5,
        rank_last_week: 3,
        weeks_on_list: 7,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '1250209765',
        primary_isbn13: '9781250209764',
        publisher: 'Flatiron',
        description: 'A bookseller flees Mexico for the United States with her son while pursued by the head of a drug cartel.',
        price: 0,
        title: 'AMERICAN DIRT',
        author: 'Jeanine Cummins',
        contributor: 'by Jeanine Cummins',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9781250209764.jpg',
        book_image_width: 326,
        book_image_height: 495,
        amazon_product_url: 'https://www.amazon.com/American-Dirt-Oprahs-Book-Club/dp/1250209765?tag=NYTBS-20',
        age_group: '',
        book_review_link: 'https://www.nytimes.com/2020/01/17/books/review-american-dirt-jeanine-cummins.html',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/ea1c7a1f-1743-57a8-b210-0150f87a4b47'
    },
    {
        rank: 6,
        rank_last_week: 1,
        weeks_on_list: 2,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '0316420336',
        primary_isbn13: '9780316420334',
        publisher: 'Little, Brown',
        description: 'The 12th book in the Michael Bennett series. A serial-killing spree might impact national security.',
        price: 0,
        title: 'BLINDSIDE',
        author: 'James Patterson and James O Born',
        contributor: 'by James Patterson and James O. Born',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780316420334.jpg',
        book_image_width: 319,
        book_image_height: 495,
        amazon_product_url: 'https://www.amazon.com/Blindside-Michael-Bennett-James-Patterson/dp/0316420336?tag=NYTBS-20',
        age_group: '',
        book_review_link: '',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/419c0dfc-b822-5fbe-844d-e8143f9f2bb1'
    },
    {
        rank: 7,
        rank_last_week: 0,
        weeks_on_list: 1,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '1250202035',
        primary_isbn13: '9781250202031',
        publisher: "St. Martin's",
        description: 'Shay Miller’s bad luck may get even worse when she meets a pair of sisters who always get what they want.',
        price: 0,
        title: 'YOU ARE NOT ALONE',
        author: 'Greer Hendricks and Sarah Pekkanen',
        contributor: 'by Greer Hendricks and Sarah Pekkanen',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9781250202031.jpg',
        book_image_width: 329,
        book_image_height: 500,
        amazon_product_url: 'https://www.amazon.com/dp/1250202035?tag=NYTBSREV-20&tag=NYTBS-20',
        age_group: '',
        book_review_link: '',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/2ca16350-9c24-51cd-8025-d4fea9e097fb'
    },
    {
        rank: 8,
        rank_last_week: 0,
        weeks_on_list: 1,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '0802148530',
        primary_isbn13: '9780802148537',
        publisher: 'Grove',
        description: 'Casey Peabody goes through a big life transition as she tries to maintain a creative life.',
        price: 0,
        title: 'WRITERS & LOVERS',
        author: 'Lily King',
        contributor: 'by Lily King',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780802148537.jpg',
        book_image_width: 330,
        book_image_height: 500,
        amazon_product_url: 'https://www.amazon.com/dp/0802148530?tag=NYTBSREV-20&tag=NYTBS-20',
        age_group: '',
        book_review_link: 'https://www.nytimes.com/2020/03/03/books/review/writers-lovers-by-lily-king-an-excerpt.html',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/753c6a34-8498-5a8f-821d-9c152863f32a'
    },
    {
        rank: 9,
        rank_last_week: 5,
        weeks_on_list: 40,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '1250301696',
        primary_isbn13: '9781250301697',
        publisher: 'Celadon',
        description: 'Theo Faber looks into the mystery of a famous painter who stops speaking after shooting her husband.',
        price: 0,
        title: 'THE SILENT PATIENT',
        author: 'Alex Michaelides',
        contributor: 'by Alex Michaelides',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9781250301697.jpg',
        book_image_width: 326,
        book_image_height: 495,
        amazon_product_url: 'https://www.amazon.com/Silent-Patient-Alex-Michaelides/dp/1250301696?tag=NYTBS-20',
        age_group: '',
        book_review_link: '',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object], [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/fe8f9863-f798-55c5-acdf-ceb32b5484ce'
    },
    {
        rank: 10,
        rank_last_week: 0,
        weeks_on_list: 1,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '0062671189',
        primary_isbn13: '9780062671189',
        publisher: 'Harper',
        description: 'As a bill that may hurt the rights of Native Americans goes to Congress in 1953, domestic issues arise for plant workers near the Turtle Mountain Reservation in North Dakota.',
        price: 0,
        title: 'THE NIGHT WATCHMAN',
        author: 'Louise Erdrich',
        contributor: 'by Louise Erdrich',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780062671189.jpg',
        book_image_width: 331,
        book_image_height: 500,
        amazon_product_url: 'https://www.amazon.com/dp/0062671189?tag=NYTBSREV-20&tag=NYTBS-20',
        age_group: '',
        book_review_link: 'https://www.nytimes.com/2020/03/03/books/review/night-watchman-louise-erdrich.html',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/d37bbfca-b750-5a5c-ad3a-3495748aeae1'
    },
    {
        rank: 11,
        rank_last_week: 0,
        weeks_on_list: 1,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '039918189X',
        primary_isbn13: '9780399181894',
        publisher: 'Ballantine',
        description: 'Old pains are unpacked as the fractured Perkins family goes on a trip through Europe.',
        price: 0,
        title: 'THE JETSETTERS',
        author: 'Amanda Eyre Ward',
        contributor: 'by Amanda Eyre Ward',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780399181894.jpg',
        book_image_width: 331,
        book_image_height: 500,
        amazon_product_url: 'https://www.amazon.com/dp/039918189X?tag=NYTBSREV-20&tag=NYTBS-20',
        age_group: '',
        book_review_link: 'https://www.nytimes.com/2020/02/21/books/review/the-jetsetters-amanda-eyre-ward.html',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/547223d3-403e-5262-b6c4-4eac04e1af33'
    },
    {
        rank: 12,
        rank_last_week: 9,
        weeks_on_list: 10,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '052554190X',
        primary_isbn13: '9780525541905',
        publisher: 'Putnam',
        description: 'Tumult ensues when Alix Chamberlain’s babysitter is mistakenly accused of kidnapping her charge.',
        price: 0,
        title: 'SUCH A FUN AGE',
        author: 'Kiley Reid',
        contributor: 'by Kiley Reid',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780525541905.jpg',
        book_image_width: 328,
        book_image_height: 495,
        amazon_product_url: 'https://www.amazon.com/Such-Fun-Age-Kiley-Reid/dp/052554190X?tag=NYTBS-20',
        age_group: '',
        book_review_link: 'https://www.nytimes.com/2019/12/31/books/review/such-a-fun-age-kiley-reid.html',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/f2ec30bb-ddd2-5f4a-a17c-34c574bf1bf7'
    },
    {
        rank: 13,
        rank_last_week: 8,
        weeks_on_list: 24,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '0062963678',
        primary_isbn13: '9780062963673',
        publisher: 'Harper',
        description: 'A sibling relationship is impacted when the family goes from poverty to wealth and back again over the course of many decades.',
        price: 0,
        title: 'THE DUTCH HOUSE',
        author: 'Ann Patchett',
        contributor: 'by Ann Patchett',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780062963673.jpg',
        book_image_width: 328,
        book_image_height: 495,
        amazon_product_url: 'https://www.amazon.com/Dutch-House-Novel-Ann-Patchett/dp/0062963678?tag=NYTBS-20',
        age_group: '',
        book_review_link: 'https://www.nytimes.com/2019/09/21/books/review-dutch-house-ann-patchett.html',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object], [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/0ad5db6c-4d15-5624-bef3-1385f93f78e2'
    },
    {
        rank: 14,
        rank_last_week: 0,
        weeks_on_list: 1,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '073521672X',
        primary_isbn13: '9780735216723',
        publisher: 'Riverhead',
        description: 'In 1969, secrets in a South Brooklyn neighborhood are uncoverd when a church deacon known as Sportcoat shoots a drug dealer in public.',
        price: 0,
        title: 'DEACON KING KONG',
        author: 'James McBride',
        contributor: 'by James McBride',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780735216723.jpg',
        book_image_width: 336,
        book_image_height: 500,
        amazon_product_url: 'https://www.amazon.com/dp/073521672X?tag=NYTBSREV-20&tag=NYTBS-20',
        age_group: '',
        book_review_link: 'https://www.nytimes.com/2020/02/29/books/review/deacon-king-kong-james-mcbride.html',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/ec978683-f109-562a-924c-0c7186db9547'
    },
    {
        rank: 15,
        rank_last_week: 10,
        weeks_on_list: 22,
        asterisk: 0,
        dagger: 0,
        primary_isbn10: '0399562486',
        primary_isbn13: '9780399562488',
        publisher: 'Pamela Dorman/Viking',
        description: 'In Depression-era Kentucky, five women refuse to be cowed by men or convention as they deliver books.',
        price: 0,
        title: 'THE GIVER OF STARS',
        author: 'Jojo Moyes',
        contributor: 'by Jojo Moyes',
        contributor_note: '',
        book_image: 'https://s1.nyt.com/du/books/images/9780399562501.jpg',
        book_image_width: 328,
        book_image_height: 495,
        amazon_product_url: 'https://www.amazon.com/Giver-Stars-Novel-Jojo-Moyes/dp/0399562486?tag=NYTBS-20',
        age_group: '',
        book_review_link: '',
        first_chapter_link: '',
        sunday_review_link: '',
        article_chapter_link: '',
        isbns: [ [Object], [Object], [Object] ],
        buy_links: [ [Object], [Object], [Object], [Object], [Object] ],
        book_uri: 'nyt://book/0365e66e-8090-5ec1-8d8c-2ed89027d374'
    }
]